[package]
name = "dms-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# packparse = { path = "../packparse", optional = true }
# modparser = { path = "../modparser", optional = true }
# modrinth = { path = "../modrinth", optional = true }
# hangar = { path = "../hangar", optional = true }
denji = { path = "../denji" }
mar = { path = "../mar" }

serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
log = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }

owo-colors = "4.1.0"
chrono = { version = "0.4.38", default-features = false, features = [
  "std",
  "clock",
] }
fern_colored = { version = "0.6.1", features = ["colored"] }
tower-http = { version = "0.6.1", features = ["cors"] }
http = "1.1.0"
directories = "5.0.1"
axum = { version = "0.7.7", features = ["ws"] }

[build-dependencies]
anyhow.workspace = true

[lints]
workspace = true

[features]
default = []

# all-providers = ["provider-modrinth", "provider-hangar", "provider-curse"]
# provider-modrinth = ["dep:modrinth"]
# provider-hangar = ["dep:hangar"]
# provider-curse = []

# all-parsers = ["parser-modpack", "parser-modjar"]
# parser-modpack = ["dep:packparse"]
# parser-modjar = ["dep:modparser"]

# dms = ["all-providers", "all-parsers"]
