[package]
name = "elytra"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
thiserror.workspace = true
log.workspace = true
tokio.workspace = true

reqwest = { workspace = true, optional = true }
zip = { workspace = true, optional = true }
bitflags = { version = "2.6.0", features = ["serde"], optional = true }
chrono = { version = "0.4.38", default-features = false, features = [
  "std",
  "serde",
], optional = true }


[features]
default = ["providers-modrinth", "utils-modpack", "utils-mod"]

providers-base = ["dep:reqwest"]
providers-hangar = ["providers-base", "dep:bitflags", "dep:chrono"]
providers-modrinth = ["providers-base"]

utils-base = ["dep:zip"]
utils-modpack = ["utils-base"]
utils-mod = ["utils-base"]

[lints]
workspace = true

[dev-dependencies]
env_logger = "0.11.5"
toml = "0.8.19"
serde_urlencoded = "0.7.1"
serde_json.workspace = true
