[package]
name = "elytra"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
log = { workspace = true, optional = true }

reqwest = { workspace = true, optional = true }
zip = { workspace = true, optional = true }
bitflags = { version = "2.6.0", features = ["serde"], optional = true }
chrono = { version = "0.4.38", default-features = false, features = [
  "std",
  "serde",
], optional = true }
libloading = { version = "0.8.6", optional = true }

mar = { path = "../mar", default-features = false, optional = true }

[features]
default = ["providers-modrinth", "manifest"]

providers-base = ["dep:reqwest"]
providers-hangar = ["providers-base", "dep:bitflags", "dep:chrono"]
providers-modrinth = ["providers-base"]

utils-base = [""]
utils-modpack = ["utils-base", "dep:zip"]
utils-mod = ["utils-base", "dep:zip"]
utils-plugin = ["dep:libloading", "dep:thiserror", "plugin"]

manifest = ["dep:serde", "dep:log", "dep:thiserror"]
plugin = ["mar/type-maven-artifact"]

[lints]
workspace = true

[dev-dependencies]
env_logger = "0.11.5"
toml = "0.8.19"
serde_urlencoded = "0.7.1"
serde_json.workspace = true
tokio.workspace = true
