[package]
name = "denji"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.30"
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
reqwest = { workspace = true, features = ["stream"] }
mar = { path = "../mar" }

[dev-dependencies]
env_logger.workspace = true
tokio.workspace = true
humantime = "2.1.0"
tempdir = "0.3.7"

[lints]
workspace = true
